### PR TITLE
Add simple testsuite

### PR DESCRIPTION
**Pull request by dcermak**
This is a WIP pull request to add a integration test suite for obs-service-node-modules.

Currently you need podman and buildah installed and can execute it as follows:
```ShellSession
$ poetry install
$ poetry run pytest -vv -n 4 .
# now wait…
```

### CODE REVIEW

**Comment by dcermak** [comment]
@lnussel @AdamMajer Could you please take a look, I'd consider this a viable prototype for now.

Please let me know if it is lacking anything that you wish to have.

**Review by SchoolGuy — APPROVED** [review]
Although I am not maintainer of this tool, I would deem this PR as LGTM.

**Comment by dcermak** [comment]
@lnussel @AdamMajer Could you please take a look?

**Review by AdamMajer — APPROVED** [review]
Thank you, LGTM

**Pull request merged**
